//
//  CardDetailRouter.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/24/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CardDetailRoutingLogic
{
  
}

protocol CardDetailDataPassing
{
  var dataStore: CardDetailDataStore? { get }
}

class CardDetailRouter: NSObject, CardDetailRoutingLogic, CardDetailDataPassing
{
  weak var viewController: CardDetailViewController?
  var dataStore: CardDetailDataStore?
  
 
}
