//
//  CardDetailPresenter.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/24/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardDetailPresentationLogic
{
    func presentDataOnLoad(response: CardDetail.FetchDataOnLoad.Response)
}
protocol CardDetailDisplayLogic: class
{
    func displayDataOnLoad(viewModel: CardDetail.FetchDataOnLoad.ViewModel)
}

final class CardDetailPresenter: CardDetailPresentationLogic
{
  weak var viewController: CardDetailDisplayLogic?
  
    func presentDataOnLoad(response: CardDetail.FetchDataOnLoad.Response) {
        viewController?.displayDataOnLoad(viewModel: CardDetail.FetchDataOnLoad.ViewModel(cardVM: response.card?.toViewModel() ?? CardListViewModel()))
    }
 
}
