//
//  CardDetailInteractor.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/24/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardDetailBusinessLogic
{
    func fetchDataOnLoad()
}

protocol CardDetailDataStore
{
   var card: CardList? {get set}
}

final class CardDetailInteractor: CardDetailBusinessLogic, CardDetailDataStore
{
    
  var presenter: CardDetailPresentationLogic?
  var card: CardList?
    
    func fetchDataOnLoad() {
        presenter?.presentDataOnLoad(response: CardDetail.FetchDataOnLoad.Response(card: card))
    }
}

