//
//  CardDetailInteractorTests.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/24/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SafeBoda
import XCTest

class CardDetailInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CardDetailInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCardDetailInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCardDetailInteractor()
  {
    sut = CardDetailInteractor()
  }
  
  // MARK: Test doubles
  
  class CardDetailPresentationLogicSpy: CardDetailPresentationLogic
  {
    var presentDataOnLoadWasCalled = false
    func presentDataOnLoad(response: CardDetail.FetchDataOnLoad.Response) {
        presentDataOnLoadWasCalled = true
    }
    
  
  }
  
  // MARK: Tests
  
  func testFetchDataOnLoad()
  {
    let spy = CardDetailPresentationLogicSpy()
    sut.presenter = spy
    sut.fetchDataOnLoad()
    XCTAssertTrue(spy.presentDataOnLoadWasCalled, "fetchDataOnLoad() should ask the presenter to format the result")
  }
}
