//
//  SearchPresenter.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/23/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentError(response: Search.ResponseError.Response)
    func presentCards(response: Search.Search.Response)
    func presentLoader()
}

protocol SearchDisplayLogic: class
{
    func displayError(viewModel: Search.ResponseError.ViewModel)
    func displayCards(viewModel: Search.Search.ViewModel)
    func displayLoader()
}

final class SearchPresenter: SearchPresentationLogic
{
  weak var viewController: SearchDisplayLogic?

    func presentCards(response: Search.Search.Response) {
        viewController?.displayCards(viewModel: Search.Search.ViewModel(cardsVM: response.cards.map({$0.toViewModel()})))
    }
    
    func presentError(response: Search.ResponseError.Response) {
        viewController?.displayError(viewModel: Search.ResponseError.ViewModel(message: response.error.localizedDescription))
    }
    
    func presentLoader() {
        viewController?.displayLoader()
    }
}
