//
//  SearchModels.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/23/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
    
    struct ViewModel {
        var cardsVM: [CardListViewModel] = []
        var message:String = ""
        var isSearchBarVisible = false
        var searchHeight: CGFloat = 56.0
    }
    
    enum Search {
        struct Request {
            var query: String
        }
        
        struct Response {
            var cards: [CardList]
        }
        
        struct ViewModel {
            var cardsVM: [CardListViewModel] = []
        }
    }
    
    enum ResponseError {
        struct Response {
            var error: Error
        }
        
        struct ViewModel {
            var message:String = ""
        }
    }
    
    enum ProcessCardTap {
        struct Request {
            var id: String
        }
    }
}
