//
//  SearchRouter.swift
//  SafeBoda
//
//  Created by Achem Samuel on 6/23/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic
{
    func routeToCardDetail(segue: UIStoryboardSegue?)
}

protocol SearchDataPassing
{
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing
{
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    func routeToCardDetail(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: CardDetailViewController.storyboardName, bundle: nil)
        guard let destinationVC = storyboard.instantiateViewController(withIdentifier: CardDetailViewController.STORYBOARD_ID) as? CardDetailViewController else {return}
        var destinationDS = destinationVC.router!.dataStore!
        passDataToCardDetail(source: dataStore!, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    func passDataToCardDetail(source: SearchDataStore, destination: inout CardDetailDataStore)
    {
        destination.card = source.selectedCard
    }
}
